# Generated by Django 4.1.5 on 2023-02-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='grupo',
            field=models.CharField(choices=[('OT', 'Oficina Técnica'), ('SP', 'Supervisor'), ('PP', 'Preparador'), ('JB', 'Jefe de Bodega')], default='', max_length=40),
        ),
    ]
