# Generated by Django 4.1.5 on 2023-02-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Inventario',
            fields=[
                ('id_detalle_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_inventariada', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Detalle de inventario',
                'verbose_name_plural': 'Detalle de inventarios',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id_familia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_familia', models.CharField(max_length=100)),
                ('is_active', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventaro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inventario', models.DateField(blank=True, null=True)),
                ('is_active_inventario', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
        ),
    ]
