# Generated by Django 4.1.5 on 2023-02-03 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
        ('vale_consumo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalle_inventario',
            name='no_inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventario'),
        ),
        migrations.AddField(
            model_name='detalle_inventario',
            name='recurso_inventariado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vale_consumo.recurso'),
        ),
    ]
