# Generated by Django 4.1.6 on 2023-02-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vale_consumo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado_solicitud',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado'), ('Rechazado', 'Rechazado'), ('LE', 'Listo paa entrega')], default='Pendiente', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='is_active_solicitud',
            field=models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, null=True),
        ),
    ]
