# Generated by Django 4.1.5 on 2023-01-31 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vale_consumo', '0002_alter_solicitud_bodega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vale_consumo.bodega'),
        ),
    ]
