# Generated by Django 4.1.5 on 2023-02-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vale_consumo', '0005_alter_solicitud_preparador'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='observacion',
            field=models.CharField(blank=True, choices=[('Observación 1', 'Observación 1'), ('Observación 2', 'Observación 2'), ('Observación 3', 'Observación 3'), ('Observación 4', 'Observación 4')], default='Observación 1', max_length=100, null=True),
        ),
    ]
