# Generated by Django 4.1.5 on 2023-02-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vale_consumo', '0006_solicitud_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado_solicitud',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado'), ('Rechazado', 'Rechazado'), ('LE', 'Listo paa entrega')], default='Pendiente', max_length=10),
        ),
    ]
