# Generated by Django 4.1.5 on 2023-02-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vale_consumo', '0007_alter_solicitud_estado_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro_costo',
            name='cc',
            field=models.CharField(default='aa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centro_costo',
            name='comentario',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centro_costo',
            name='crr',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centro_costo',
            name='g_part',
            field=models.CharField(default='aa', max_length=100),
            preserve_default=False,
        ),
    ]
